export enum roleEnum {
  RECRUITER = 'RECRUITER',
  RECRUIT = 'APPLICANT',
}
export enum SkillLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
}
export enum JobLevel {
  BEGINNER = 'BEGINNER',
  INTERMEDIATE = 'INTERMEDIATE',
  ADVANCED = 'ADVANCED',
}
export enum JobType {
  FULLTIME = 'FULLTIME',
  PARTTIME = 'PARTTIME',
  INTERNSHIP = 'INTERNSHIP',
  REMOTE = 'REMOTE',
  FREELANCE = 'FREELANCE',
}
export enum SalaryType {
  CRYPTO = 'CRYPTO',
  FIAT = 'FIAT',
}

export enum ApplicantStatus {
  NOTVIEWED = 'NOTVIEWED',
  SHORTLISTED = 'SHORTLISTED',
  SELECTED = 'SELECTED',
  REJECTED = 'REJECTED',
}
